version: '3.4'

services:
  Nas:
    image: dperson/samba
    environment:
      TZ: 'Asia/Kolkata'
      USERID: 1000
      GROUPID: 1000
      NMBD: 'true'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: false
    tty: false
    volumes:
      - /mnt/Media/share/:/mount:z
      - /mnt/TimeMachine/:/TimeMachine:z
      - /mnt/Media/shareData/:/Data:z
    command: '-s "NAS;/mount;yes;no;no;nandu,nandujagdish" -s "Airport;/TimeMachine;yes;no;no;nandu,nandujagdish" -s "Data;/Data;yes;no;no;nandujagdish" -u "nandujagdish;ubroot" -u "nandu;nandu"  -p'

networks:
  default: