version: "3.8"
services:
    aria2Backend:
        image: p3terx/aria2-pro
        container_name: aria2Backend
        environment:
        - PUID=1000
        - PGID=1000
        - TZ='Asia/Kolkata'
        - RPC_PORT=6800
        - LISTEN_PORT=6888
        - RPC_SECRET=ubroot
        volumes:
        - /home/ubuntu/Docker_ContainerData/Aria2:/config
        - /mnt/Media/share/Downloads/:/downloads
        ports:
        - 6888:6888
        - 6888:6888/udp
        - 6800:6800
        restart: unless-stopped

    aria2UI:
        image: p3terx/ariang
        container_name: aria2UI
        ports:
        - 6880:6880
        restart: unless-stopped
        labels:
            # required when using --providers.docker.exposedbydefault=false
            - "traefik.enable=true"
            - "traefik.http.routers.aria.rule=Host(`aria.home.com`)"
            - "traefik.http.routers.aria.entrypoints=http"
            # - "traefik.docker.network=discovery"
            - "traefik.http.services.aria.loadbalancer.server.port=6880"


    transmission:
        image: linuxserver/transmission
        container_name: transmission
        environment:
          - PUID=1000
          - PGID=1000
          - TZ='Asia/Kolkata'
          - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
          - USER=doc #optional
          - PASS=doc123 #optional
        volumes:
          - /home/ubuntu/Docker_ContainerData/Transmission/config:/config
          - /mnt/Media/share/Downloads/:/downloads
          - /home/ubuntu/Docker_ContainerData/Transmission/watch:/watch
        ports:
          - 9091:9091
          - 51413:51413
          - 51413:51413/udp
        restart: unless-stopped
        labels:
            # required when using --providers.docker.exposedbydefault=false
            - "traefik.enable=true"
            - "traefik.http.routers.transmission.rule=Host(`transmission.home.com`)"
            - "traefik.http.routers.transmission.entrypoints=http"
            # - "traefik.docker.network=discovery"
            - "traefik.http.services.transmission.loadbalancer.server.port=9091"

    plex:
        image: linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - PLEX_CLAIM=claim-ZShpe--SnWeKYnq5xQ1p
        volumes:
            - /home/ubuntu/Docker_ContainerData/Plex/:/config
            - /mnt/Media/share/TVShows/:/tv
            - /mnt/Media/share/Movies/:/movies
        restart: unless-stopped
     
    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "67:67/udp"
        - "8053:80/tcp"
        # - "443:443/tcp"
        environment:
        - ServerIP=192.168.1.11
        - PROXY_LOCATION='pihole'
        # - VIRTUAL_HOST='pihole.homeserver.lan'
        - VIRTUAL_PORT=80
        - TZ='Asia/Kolkata'
        - WEBPASSWORD='ubroot'
        # Volumes store your data between container upgrades
        volumes:
        - '/home/ubuntu/Docker_ContainerData/pihole/:/etc/pihole/'
        - '/home/ubuntu/Docker_ContainerData/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
        dns:
        - 127.0.0.1
        - 1.1.1.1
        # Recommended but not required (DHCP needs NET_ADMIN)
        #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        cap_add:
        - NET_ADMIN
        restart: unless-stopped
        labels:
            # required when using --providers.docker.exposedbydefault=false
            - "traefik.enable=true"
            - "traefik.http.routers.pihole.rule=Host(`pihole.home.com`)"
            - "traefik.http.routers.pihole.entrypoints=http"
            # - "traefik.docker.network=discovery"
            - "traefik.http.services.pihole.loadbalancer.server.port=80"

    portainer:
        container_name: portainer
        image: portainer/portainer
        ports: 
        - "9000:9000/tcp"
        volumes: 
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/home/ubuntu/Docker_ContainerData/Portainer/:/data"
        restart: unless-stopped
        labels:
            # required when using --providers.docker.exposedbydefault=false
            - "traefik.enable=true"
            - "traefik.http.routers.portainer.rule=Host(`portainer.home.com`)"
            - "traefik.http.routers.portainer.entrypoints=http"
            # - "traefik.docker.network=discovery"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    Nas:
        container_name: Nas
        image: dperson/samba
        environment:
            TZ: 'Asia/Kolkata'
            USERID: 1000
            GROUPID: 1000
            NMBD: 'true'
        networks:
            - default
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        read_only: false
        tmpfs:
            - /tmp
        restart: unless-stopped
        stdin_open: false
        tty: false
        volumes:
            - /mnt/Media/share/:/mount:z
            - /mnt/TimeMachine/:/TimeMachine:z
            - /mnt/Media/shareData/:/Data:z
        command: '-g "fruit:aapl = yes" -g "vfs objects = catia fruit streams_xattr" -g "fruit:model = MacSamba" -g "fruit:time machine = yes" -g "durable handles = yes" -g "kernel oplocks = no" -g "kernel share modes = no" -g "posix locking = no" -g "fruit:advertise_fullsync = true" -g "smb2 leases = yes" -s "NAS;/mount;yes;no;no;nandu,nandujagdish" -s "Airport;/TimeMachine;yes;no;no;nandu,nandujagdish" -s "Data;/Data;yes;no;no;nandujagdish" -u "nandujagdish;ubroot" -u "nandu;nandu"  -p'
    Watchtower:
        container_name: Watchtower
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            WATCHTOWER_CLEANUP: 'true'
            WATCHTOWER_POLL_INTERVAL: 3000
        restart: unless-stopped
    traefik:
        container_name: traefik
        domainname: homedomain.lan
    
        image: traefik:v2.2
        restart: unless-stopped
        # Note I opt to whitelist certain apps for exposure to traefik instead of auto discovery
        # use `--providers.docker.exposedbydefault=true` if you don't want to have to do this
        command:
            - "--providers.docker=true"
            # - "--providers.docker.network=discovery"
            - "--providers.docker.exposedbydefault=false"
            - "--api.insecure=true"
            - "--api.dashboard=true"
            - "--entrypoints.http.address=:80"
            - "--log.level=DEBUG"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            - default
            # - discovery
        dns:
            - 127.0.0.1
            - 1.1.1.1
        
      

#    reverse-proxy:
#        # The official v2 Traefik docker image
#        image: traefik:v2.2
#        # Enables the web UI and tells Traefik to listen to docker
#        command: --api.insecure=true --providers.docker
#        ports:
#            # The HTTP port
#            - "80:80"
#            # The Web UI (enabled by --api.insecure=true)
#            - "8080:8080"
#        volumes:
#            # So that Traefik can listen to the Docker events
#            - /var/run/docker.sock:/var/run/docker.sock
      