
    version: "2.1"
    services:
      plex:
        image: linuxserver/plex
        container_name: plex
        network_mode: host
        environment:
          - PUID=1000
          - PGID=1000
          - VERSION=docker
          - PLEX_CLAIM=claim-ZShpe--SnWeKYnq5xQ1p
        volumes:
          - /mnt/Media/Docker_ContainerData/Plex/:/config
          - /mnt/Media/share/TVShows/:/tv
          - /mnt/Media/share/Movies/:/movies
        restart: unless-stopped