version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ='Asia/Kolkata'
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=doc #optional
      - PASS=doc123 #optional
    volumes:
      - /mnt/Media/Docker_ContainerData/Transmission/config:/config
      - /mnt/Media/share/Downloads/:/downloads
      - /mnt/Media/Docker_ContainerData/Transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped